Lesson 7 Ajax(Part #2)
Fatpaher/think_qa pull request #5
Opened 2017-02-21 13:55 UTC by Fatpaher

- only author can edit his question
- only author can edit his answer
- rework deletion of answers with ajax
- author of question can select right answer
- author of questino can re-select right answer
- right answer shows at the top of answers list

2017-02-22 07:43 UTC, vkurennov requested changes

2017-02-22 07:43 UTC, vkurennov commented on app/controllers/best_answers_controller.rb
> +class BestAnswersController < ApplicationController
Лучший ответ - это **действие** над ответом, а не самостоятельный ресурс. Поэтому, лучше сделать кастомный экшн в AnswersController

2017-02-22 07:43 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @question = Question.find(params[:question_id])
А зачем грузить вопрос по id, когда можно получить его из ассоциаций ответа? И объяви ресурс answers как shallow в роутах, чтобы не нужно было передавать question_id там, где можно этого не делать.

2017-02-22 07:43 UTC, vkurennov commented on app/controllers/best_answers_controller.rb
> +      @question.answers.where.not(id: @answer.id).update_all(best_answer: false)
Вся эта логика (с этой строки и далее) - это бизнес-логика, т.е. логика, иземняющая состояние системы. Ей не место в контроллере (об этом еще чуть позже поговорим), ей место на уровне моделей. А контроллер должен просто у модели вызывать нужный метод и возвращать ответ.

2017-02-22 07:43 UTC, vkurennov commented on app/controllers/best_answers_controller.rb
> +      @question.answers.where.not(id: @answer.id).update_all(best_answer: false)
И еще: т.к. у тебя происходит изменение нескольких объектов, то стоит применить [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарными

2017-02-22 07:43 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
Дублирование, вынести в метод и фильтр

2017-02-22 07:43 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    return unless current_user.author_of?(@question)
А какой ответ будт отрендерен в этом случае? Нужно же что-то в ответ на запрос вернуть осмысленное.

2017-02-22 07:43 UTC, vkurennov commented on app/views/answers/create.js.erb
>  $('.answers').append('<%= j render @answer %>');
То есть, append будет в любом случае, даже если была ошибка валидации? А как тогда ссылки на удаление, скажем, будут отрендерены, ведь ответ еще не имеет id?

2017-02-22 07:43 UTC, vkurennov commented on app/views/answers/destroy.js.erb
> +$(".answers").html('<%= j render @question.answers %>');
Надо удалять только удаленный ответ, без рендеринга всего списка

2017-02-22 07:43 UTC, vkurennov commented on app/views/answers/update.js.erb
> +  $(".answers").html('<%= j render @question.answers %>');
Нужно обновлять только изменненый ответ, а не рендрить список заново

2017-02-22 07:43 UTC, vkurennov commented on app/views/best_answers/update.js.erb
> +$(".answers").html('<%= j render @question.answers %>');
А тут можно весь список отрендерить, иначе, слишком сложный js может быть

2017-02-22 07:43 UTC, vkurennov commented on config/routes.rb
> +    resources :answers, only: [:create, :update, :destroy]
Сделай ресурс shallow

2017-02-22 07:43 UTC, vkurennov commented on config/routes.rb
> +    resources :best_answers, only: [:update]
Это должен быть кастомный экшн для ответа, а не отдельный ресурс

2017-02-22 12:32 UTC, vkurennov requested changes

2017-02-22 12:32 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@question)
А если не автор, что тогда?

2017-02-22 12:32 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
Не исправлено. У тебя такая же строчка в destroy, например

2017-02-22 12:32 UTC, vkurennov commented on app/models/answer.rb
> +      self.best_answer = true
Используй `update!`

2017-02-22 12:32 UTC, vkurennov commented on spec/features/user_can_re-select_best_answer_spec.rb
> +feature 'author of question can re-select best answer' do
Это не отдельная фича, а просто сценарий в фиче про лучший ответ

2017-02-22 12:32 UTC, vkurennov commented on spec/features/user_can_re-select_best_answer_spec.rb
> +    _best_answer = create(:answer, :best_answer, question_id: question.id, created_at: 1.day.ago)
А зачем тут подчеркивания в названии? Можно вообще без переменных обойтись, они же не используются нигде

2017-02-22 12:32 UTC, vkurennov commented on app/models/answer.rb
> +  def select_best
А где тест модели на этот метод?

2017-02-22 12:39 UTC, Fatpaher commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
@vkurennov в  методе destroy мне не нужна переменная экзепляра

2017-02-22 13:05 UTC, Fatpaher commented on spec/features/user_can_re-select_best_answer_spec.rb
> +    _best_answer = create(:answer, :best_answer, question_id: question.id, created_at: 1.day.ago)
@vkurennov  подчеркивание используется для не исмользуемых переменных [здесь](http://stackoverflow.com/questions/8689673/marking-an-unused-block-variable) это расписано. Я знаю что можно не их не называть, но для того чтобы тест был более понятен предпочитаю это делать

2017-02-22 13:08 UTC, Fatpaher commented on spec/features/user_can_re-select_best_answer_spec.rb
> +feature 'author of question can re-select best answer' do
@vkurennov Ну в задании это было написано как отдельная фича поэтому я и вынес его отдельно

2017-02-23 07:03 UTC, vkurennov commented on spec/features/user_can_re-select_best_answer_spec.rb
> +    _best_answer = create(:answer, :best_answer, question_id: question.id, created_at: 1.day.ago)
Там речь про блок идет вообще-то, когда блок передает несколько аргументов, а тебе нужен один.

2017-02-23 07:06 UTC, vkurennov approved these changes

2017-02-23 07:06 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
Ну то есть, будет полное дублирование только из-за того, что в одном случае локальная переменная, а в другом инстанс?

2017-02-23 07:06 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.best_answer).to be_truthy
`expect(answer).to be_best`

2017-02-23 07:06 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(previos_best_answer.best_answer).to be_falsy
`expect(previos_best_answer).to_not be_best`

2017-02-23 14:59 UTC, merged